### ISSUE TITLE
Request https://nx.dev/ 

### ISSUE THREAD

**Issue by st-clair-clarke** [sonyarianto/jogja#1]
Requesting [nx](https://nx.dev/) CLI to be added.

**Comment by sonyarianto** [comment]
@st-clair-clarke thanks for the request, hmmm just know about NX, I will add, funny things, when I run `npx create-nx-workspace@latest jogja_nx` it will create new folder `jogja_nx` but the CLI refering to `jogja-nx` internally, so when finished preparing it tries to  go to directory `jogja-nx` which is not there.

I am testing it on Windows.

But anyway I will add this CLI to Jogja.

**Comment by sonyarianto** [comment]
@st-clair-clarke ok I just release 0.2.5 that contains the Nx command and several new features. Just update with `npm i -g jogja` to get the latest version.

**Comment by st-clair-clarke** [comment]
After installation I received the following terminal printout:

`success: installed jogja@0.2.6 with executables: jogja, yogyakarta, yogya`

The second executable seems similar to the first but the third does nothing that I can see? Were these additional executables meant to be there? If so, could you please update the docs? 

Cheers

**Comment by sonyarianto** [comment]
@st-clair-clarke ok just ignore that, I already released the latest version again 0.2.7, update it `npm i -g jogja`. Now I removed the additional command alias. Now only `jogja`.

PS. In the latest updated I added Blitz.js and VitePress, it you have know any other missing framework please let me know.

Thank you very much for the report.
